### ISSUE TITLE
Code / data availability checklist

### ISSUE THREAD

**Issue by emdann** [Teichlab/Pan_fetal_immune#46]
### Pre-submission
- [x] **Are all bits of analysis in the code repository?**
	- [x] Missing script/code to run cpdb analysis (can be a .sh)
	 - [x] Missing scripts for preprocessing TCR/BCR data: scirpy and dandelion analysis code (to generate ​​/lustre/scratch117/cellgen/team297/kt16/panfetal/PAN.A01.v01.entire_data_normalised_log.20210429.LYMPHOID.embedding_dandelion_productive.csv)
	 - [x] Identification of maternal contaminants: souporcell call + scripts
- [x] Add conda environment yaml: one for scvi-tools and one for CPU analysis
- [x] **Data portal up and running**
	- [x] download links
	- [x] cellxgene links
	- [x] high res img links
- [x] **Check links to data in repository README** 
- [x] Add example notebooks:
	- [x] Visium data exploration
	- [x] scArches mapping
- [x] **Transfer repository to TeichLab** https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#transferring-a-repository-owned-by-your-user-account
- [x] Make repository public
---
### Post-submission
- [x] Add link to biorxiv
- [x] Contact DCP wrangling team
