### ISSUE TITLE
Improved QC and annotation checklist

### ISSUE THREAD

**Issue by emdann** [Teichlab/Pan_fetal_immune#52]
- [x] PFI
	- [x] make raw
	- [x] calculate HVGs
	- [x] 2drive
	- [x] scVI
	- [x] emb+clustering
- [x] Split and first filtering (remove mat contaminants, doublet clusters, low q samples from unusual sorts)
- [x] MYELOID_NEW
	- [x] make raw
	- [x] calculate HVGs
	- [x] 2drive
	- [x] scVI
	- [x] emb+clustering
	- [x] Save QCed version
- [x] LYMPHOID_NEW
	- [x] make raw
	- [x] calculate HVGs
	- [x] 2drive
	- [x] scVI
	- [x] emb+clustering
	- [x] Save QCed version
- [x] STROMA_NEW
	- [x] make raw
	- [x] calculate HVGs
	- [x] 2drive
	- [x] scVI
	- [x] emb+clustering
	- [x] Save QCed version
- [x] ERYTHROID_NEW
	- [x] make raw
	- [x] calculate HVGs
	- [x] 2drive
	- [x] scVI
	- [x] emb+clustering
	- [x] Save QCed version
## Post QC annotation
- [x] MYELOID_NEW_POSTQC
	- [x] calculate HVGs 
	- [x] 2drive 
	- [x] scVI
	- [x] emb+clustering
	- [ ] annotate
- [x] LYMPHOID_NEW_POSTQC
	- [x] calculate HVGs 
	- [x] 2drive 
	- [x] scVI
	- [x] emb+clustering
	- [x] make NKT view
	- [ ] annotate
- [x] STROMA_NEW_POSTQC
	- [x] calculate HVGs 
	- [x] 2drive 
	- [x] scVI
	- [x] emb+clustering
	- [ ] annotate
- [x] ERYTHROID_NEW_POSTQC
	- [x] calculate HVGs 
	- [x] 2drive 
	- [x] scVI
	- [x] emb+clustering
	- [ ] annotate
- [x] NKT_NEW_POSTQC
	- [x] calculate HVGs 
	- [x] 2drive 
	- [x] scVI
	- [x] emb+clustering
	- [ ] annotate
- [x] HSC_PROGENITORS
	- [x] Assemble from mye/lymph/ery
	- [x] calculate HVGs 
	- [x] 2drive 
	- [x] scVI
	- [x] emb+clustering
- [ ] HSC_PROGENITORS_POSTQC
	- [x] calculate HVGs 
	- [x] 2drive 
	- [x] scVI
	- [x] emb+clustering
## New assembly
- [ ] HSC_IMMUNE
	- [ ] Assemble from mye/lymph/ery
	- [ ] calculate HVGs 
	- [ ] 2drive 
	- [ ] scVI
	- [ ] emb+clustering
- [ ] PFI_POSTQC
	- [ ] Assemble from mye/lymph/ery
	- [ ] calculate HVGs 
	- [ ] 2drive 
	- [ ] scVI
	- [ ] emb+clustering

**Comment by emdann** [comment]
Improvements to implement:
- [ ] revised cell cycle gene list - [list](https://github.com/theislab/scanpy_usage/blob/master/180209_cell_cycle/data/regev_lab_cell_cycle_genes.txt) - [ref](https://www.science.org/doi/10.1126/science.aad0501)
- [ ] move ILCs to NKT embedding
